### PR TITLE
upgrading to react 15

### PR DESCRIPTION
**Pull request by johnslemmer**
I think I might have solved some of the issues different than @primeminister has.  But worth seeing and integrating what makes sense.

### CODE REVIEW

**Comment by primeminister** [comment]
Hey @johnslemmer. Great stuff man! Some of the things are the same fixes as me but you have fixed/updated more stuff, next to the router v2 and react 15.

One question: You are assigning location to props while I'm adding the location to the context. See https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#accessing-location
You do that for any reason?

**Comment by johnslemmer** [comment]
My only reason was that I feel like React is telling us to not overuse context (http://facebook.github.io/react/docs/context.html) and location looked like it only needed to go a couple layers deep. So I thought I would try just passing it through props instead.

However after looking at your fix for the same thing I think it is more appropriate to manually add location to context for now. It is a less drastic change to fix the same issue. I think moving more things to props is a larger discussion to have for reactionic down the road.

**Comment by primeminister** [comment]
Good point @johnslemmer. Will pick this up with @pors how we can ensure reactionic stays in sync with the React best practices.

**Comment by pors** [comment]
See my comment about this here: #31

**Pull request merged**
