### PR TITLE
ionItem should be able to have a link and onClick.  And big context changes.

### PR DESCRIPTION
**Pull request by johnslemmer**
I think you should be able to have an onClick handle with an ionItem link.  See my [boilerplate](https://github.com/johnslemmer/boilerplate-reactionic-meteor/blob/master/imports/ui/components/SideMenu.jsx#L49) for an example of where this might be useful.  And in my change I think passing null in to div and Link for onClick shouldn't be an issue.

### CODE REVIEW

**Comment by johnslemmer** [comment]
Also, I need to document this issue more.  And I think there is a wider issue where components when they first load may not have the correct context.  However, if context is all functions then that would alleviate the issue.

The issue I'm fixing here.  Clone my [boilerplate](https://github.com/johnslemmer/boilerplate-reactionic-meteor).  On initial login (use test/test for user/password) the side menu button won't work (the dragging method still works to get to the menu but not the button).  After doing some research the issue here is that on initial mount the context is changing when `SideMenuContainer` sets the `ionSnapper`.  However, the rest of the page will continue to render with an old context where `ionSnapper` is still set to null.  So when I try to manually toggle the side menu (using the side menu button) it won't work and throws a error in the browser console.

Like I said I think there is a larger issue with how context should only be functions like I have done here with ionGetSnapper.  I have another issue where `has-header` isn't being set properly on the content div for similar reasons.  These things don't happen all of the time.  But they do and can happen.

**Comment by johnslemmer** [comment]
Ok. last change I'm going to do today.  This should fix all the problems I've been seeing.  This one.  Clone and run my boilerplate from [this fork](https://github.com/johnslemmer/boilerplate-reactionic-meteor/tree/reactionic-issue-hasheader).  When you get to the login page if you do a hard refresh in the browser you should see the content go up behind the header.  This late commit fixes that.

So, not everyone is going to see these bugs I was seeing.  I think we can keep the old contexts (ionSnapper, ionHasHeader, etc.) around for a while.  But deprecate them.  And go through the whole reactionic codebase and start changing everything over to this PropType.func idea.  Otherwise we could have more problems in other areas down the road.

Hope all this was helpful.  And not too confusing.  I've been trying to figure out these bugs for weeks and finally came up with the right solution I think.  Let me know if you have other ideas.

**Comment by johnslemmer** [comment]
BTW.  Figuring out this whole set of bugs was spawned by [this section of the React context article](https://facebook.github.io/react/docs/context.html#updating-context) and [this](https://facebook.github.io/react/docs/context.html#known-limitations).  And I think the reason why this is happening is because `MeteorDataContainer` intermediate components between `ionBody` and something lower down the tree return false from `shouldComponentUpdate`

**Comment by johnslemmer** [comment]
Ok.  I have to add.  After playing around some more the last commit I made to address has-header issues doesn't actually fix my issue.  It actually makes things work.

I believe React can render sibling components simultaneously.  My fix for snapper works because anybody wanting to use snapper is going to be a child of SideMenuContainer.  This fix doesn't work for the `has-header` issue because thing like NavBar and IonContent are essentially siblings.  And no rendering order is guaranteed.

I will say consider just the first two commits for merging.  I think it is back to the drawing board to try and figure out my `has-header` issue.  At this point I might just hard code it as a custom class name because I know it is always going to be there.

**Comment by pors** [comment]
Hey John, looking awesome! Can you send me an email, address is here at the bottom: http://reactionic.github.io/

**Comment by pors** [comment]
@johnslemmer can you also increase the semver in package.json? I try to follow the convention that I think is common:
major version: breaks backward compatibility
minor version: added feature
patch: bug fix

So in this case I propose to increase the minor version

**Comment by johnslemmer** [comment]
will do. And then when/how do new releases get pushed up to NPM? I'm
guessing that is something you do?

**Comment by pors** [comment]
yep

**Pull request merged**
